# Generated by Django 4.0.3 on 2022-08-08 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drip54app', '0005_alter_cart_item_added_by_alter_cart_item_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_item',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
