# Generated by Django 4.0.3 on 2022-08-10 20:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drip54app', '0007_alter_cart_item_item_alter_product_product_brand_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FavoriteItems',
            new_name='Wishlist',
        ),
    ]
