# Generated by Django 4.0.3 on 2022-08-11 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drip54app', '0008_rename_favoriteitems_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clothtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clothtype', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='drip54app.clothtype'),
        ),
    ]
