# Generated by Django 4.0.3 on 2022-08-12 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drip54app', '0010_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='townorcity',
            field=models.CharField(default='Nairobi City', max_length=50),
        ),
    ]
