# Generated by Django 4.0.3 on 2022-08-12 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drip54app', '0015_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phonenumber',
            field=models.IntegerField(max_length=50, null=True),
        ),
    ]
