# Generated by Django 4.0.3 on 2022-08-13 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drip54app', '0018_checkoutitem_checkout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkoutitem',
            name='item',
        ),
        migrations.AddField(
            model_name='checkoutitem',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='drip54app.product'),
        ),
    ]
