# Generated by Django 4.0.3 on 2022-08-13 09:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drip54app', '0019_remove_checkoutitem_item_checkoutitem_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkoutitem',
            name='belongs_to',
        ),
        migrations.AddField(
            model_name='checkoutitem',
            name='belongs_to',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
