# Generated by Django 4.0.3 on 2022-08-13 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drip54app', '0020_remove_checkoutitem_belongs_to_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkoutitem',
            name='belongs_to',
        ),
        migrations.AddField(
            model_name='checkoutitem',
            name='belongs_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
