# Generated by Django 4.0.3 on 2022-08-13 12:41

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drip54app', '0022_alter_checkoutitem_belongs_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutitem',
            name='belongs_to',
            field=models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
