# Generated by Django 4.0.3 on 2022-08-14 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drip54app', '0029_order_waiting_confirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='orderitem_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
