# Generated by Django 4.0.3 on 2022-08-14 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drip54app', '0031_alter_orderitem_orderitem_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='orderitem_id',
            field=models.CharField(max_length=50),
        ),
    ]
